openapi: 3.0.0
info:
  version: "1.0"
  title: todo api
  description: Some description
servers:
  - url: http://localhost:3000/
    description: development server

paths:
  /v1/tasks:
    get:
      parameters:
        - name: pageNumber
          in: query
          description: Page Number
          schema:
            type: integer
            format: int32
            default: 1
        - name: pageSize
          in: query
          description: Page Size
          required: false
          schema:
            type: integer
            format: int32
            default: 25
      responses:
        200:
          description: List of tasks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tasksList"
  /v1/tasks/{taskId}:
    get:
      parameters:
        - name: taskId
          in: path
          description: Task Id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: List of tasks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tasksList"
components:
  schemas:
    taskDescription:
      type: string
      minLength: 2
      maxLength: 100
      example: to be perfectly clean
    task:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          minLength: 2
          maxLength: 100
          example: cleaning
        description:
          $ref: "#/components/schemas/taskDescription"
    tasksList:
      type: array
      description: list of tasks
      items:
        $ref: "#/components/schemas/task"
