openapi: 3.0.0
info:
  version: "1.0"
  title: todo api
  description: Some description
servers:
  - url: http://localhost:3000/
    description: development server

paths:
  /v1/tasks:
    get:
      responses:
        200:
          description: List of tasks
    put:
      responses:
        200:
          description: List of tasks
